### ISSUE TITLE
Script exits when "csplit --help" returns an error message

### ISSUE THREAD

**Issue by l-g** [myspaghetti/macos-guest-virtualbox#141]
I have a similar problem to #138 but I am on a Mac. This is what happens:

```
% /opt/local/bin/bash macos-guest-virtualbox.sh

                Semi-automatic installer of macOS on VirtualBox
-------------------------------------------------------------------------------

This script installs only open-source software and unmodified Apple binaries.

The script checks for dependencies and will prompt to install them if unmet.
Some stages may fail due to errant keyboard presses; run the script with
"macos-guest-virtualbox.sh stages" to see how to run only certain stages.

For iCloud and iMessage connectivity, the script needs to be edited with genuine
or genuine-like Apple parameters. macOS will work without these parameters, but
Apple-connected apps will not.

The installation requires about 40GB of available storage, 25GB for
temporary installation files and 15GB for the virtual machine. Deleting the
temporary files when prompted reduces the storage requirement by about 10GB.

Press enter to review the script settings.

vmname="macOS"             # name of the VirtualBox virtual machine
storagesize=25000          # VM disk image size in MB. minimum 22000
cpucount=2                 # VM CPU cores, minimum 2
memorysize=4096            # VM RAM in MB, minimum 2048
gpuvram=128                # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"      # VM display resolution

These values may be customized by editing them at the top of the script file.

Press enter to continue, CTRL-C to exit.

macOS detected.
Please use a package manager such as homebrew, pkgsrc, nix, or MacPorts.
Please make sure the following packages are installed and that
their path is in the PATH variable:
bash  coreutils  wget  unzip  dmg2img
Please make sure Bash and coreutils are the GNU variant.
%
```

I have all the required binaries installed through MacPorts. Bash is version 5.

Now what?

**Comment by myspaghetti** [comment]
Put the installed binaries in the `PATH` variable, for example `export PATH="/path/to/dmg2img:/opt/local/bin:${PATH}"`

You can see if it works by running `csplit --help`. If you get an error message, it's not the GNU variant of `coreutils` that's installed.

**Comment by l-g** [comment]
This is odd. 

```
% port installed coreutils    
The following ports are currently installed:
  coreutils @8.31_0 (active)
% port info coreutils     
coreutils @8.31 (sysutils)
Variants:             universal

Description:          The GNU Core Utilities are the basic file, shell, and text manipulation utilities of the GNU operating system. These are the core utilities which are
                      expected to exist on every operating system. Previously these utilities were offered as three individual sets of GNU utilities, fileutils,
                      shellutils, and textutils. Those three have been combined into a single set of utilities called the coreutils.
Homepage:             https://www.gnu.org/software/coreutils/

Extract Dependencies: xz
Library Dependencies: gettext, gmp, libiconv
Conflicts with:       gexpr
Platforms:            darwin
License:              GPL-3+
Maintainers:          none
```

So GNU Coreutils.

```
% echo $PATH              
/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

```

MacPorts is first in the $PATH.

But

```
% which csplit                
/usr/bin/csplit
```

The reason for this is that MacPorts doesn't install `csplit`, they install `**g**csplit`

```
% gcsplit --help
Usage: gcsplit [OPTION]... FILE PATTERN...
Output pieces of FILE separated by PATTERN(s) to files 'xx00', 'xx01', ...,
and output byte counts of each piece to standard output.
```

Can I just change all occurrences of csplit to gcsplit in the script?

**Comment by myspaghetti** [comment]
Yes, and I'll update the script! Thanks for the bug report!

**Comment by myspaghetti** [comment]
Fixed in [version 0.77.4](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/9268d9c70b81674e230ff40baa663ea3c579d350/macos-guest-virtualbox.sh)

**Comment by myspaghetti** [comment]
Forgot `base64`, added in [version 0.77.5](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/5e46bf03d5c9ff118687a79b3959ca62a462ad59/macos-guest-virtualbox.sh)

**Comment by l-g** [comment]
Still the same error 

_Couldn't find the requested download URL in the Apple catalog. Exiting._

Just downloaded the script from the link in the previous message.

**Comment by myspaghetti** [comment]
...that's because there's a typo in the code, sorry! [Fixed in version 0.77.7](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/f684e822400e9b1b8ec28c68d8fa9595e0e1be69/macos-guest-virtualbox.sh)

**Comment by l-g** [comment]
Still the same error. Don't you think you would save time for yourself if you tested at least the most typical usecase before releasing a new version?

**Comment by myspaghetti** [comment]
Sounds like a good idea! Would you like to buy me a test rig? A 2019 Mac Pro would be appreciated! Compiling software from source would be so much faster and save me so much time.

Fixed in version 0.77.8 -- seems I forgot `expr`!

Thanks for debugging!

**Comment by l-g** [comment]
Considering the context I would suggest you used a virtual machine for testing purposes...
